# Generated by Django 2.0.13 on 2020-02-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=20)),
                ('did', models.CharField(max_length=1000)),
                ('todo', models.CharField(max_length=1000)),
                ('ref', models.CharField(max_length=1000)),
            ],
        ),
    ]
