# Generated by Django 2.0.13 on 2020-02-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=15)),
                ('did', models.CharField(max_length=100)),
                ('do', models.CharField(max_length=100)),
            ],
        ),
    ]
